#! /bin/sh
### BEGIN INIT INFO
# Provides:          msm-log-rotate
# Required-Start:    $remote_fs $syslog $network $time
# Required-Stop:     $remote_fs $syslog $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Start-Before:    msm
# X-Stop-After:      msm
# Short-Description: Gzip log file and move it to log archives dir.
# Description:       Gzip log file and move it to log archives dir.
### END INIT INFO

# Author: Tom Offermann <tom@offermann.us>
#

# Do NOT "set -e"


# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="Gzip log file and move it to log archives dir."
NAME=msm-log-rotate
SCRIPTNAME=/etc/init.d/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
    # Nothing to do on start.
    return 1
}

#
# Function that stops the daemon/service
#
do_stop()
{
    # Roll log file
    MSM='/usr/local/bin/msm'
    if [ -x $MSM ]; then
        $MSM all logroll
        find /opt/msm/servers -name 'server.log.offset' -exec rm '{}' ';'
    else
        return 2
    fi
}

case "$1" in
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
    do_start
    case "$?" in
        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
    ;;
  stop)
    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
    do_stop
    case "$?" in
        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
    esac
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop}" >&2
    exit 3
    ;;
esac

:
